In [121]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.config import settings
# from src.aggregations import , person, labor,cadunico
import pandas as pd 
import numpy as np
from pathlib import Path

# import importlib
# importlib.reload(settings)
# importlib.reload(territorial)
# importlib.reload(person)
# importlib.reload(labor)
# importlib.reload(cadunico)

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

In [2]:
df_big_number = pd.read_csv(settings.DATA_PATH_SECTION1 / 'bignumber1.csv')

In [13]:
df_executed_by_uf = pd.read_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_uf.csv')

In [16]:
df_executed_by_state = pd.read_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_state.csv')

In [26]:
df_executed_by_pop_size = pd.read_csv(settings.DATA_PATH_SECTION1 / 'values_by_population_size.csv')

In [66]:
df_capital = pd.read_csv(settings.DATA_PATH_SECTION1 / 'aggregate_values_by_capital.csv')

In [103]:
df_zone = pd.read_csv(settings.DATA_PATH_SECTION1 / 'executed_value_by_state.csv')

In [115]:
df_territorio_especial = pd.read_csv(settings.DATA_PATH_SECTION1 / 'special_territory_w_ibge_by_brazil.csv')

In [119]:
df_territorio_especial

,Unnamed: 0,territorio,Valor (R$),Quantidade de contemplados,% recurso total,% de agentes contemplados,% população no território
0,0,Favela e Comunidade Urbana,138146185,4555,4.85,0.00,8.00
1,1,Agrupamento quilombola,7369210,481,0.26,0.00,0.70
2,2,Agrupamento indígena,5078944,254,0.18,0.00,0.83

In [120]:
4555/166000

0.027439759036144578

In [117]:
df_territorio_especial_pt2 = pd.read_csv(settings.DATA_PATH_SECTION1 / 'values_by_special_territory_uf.csv')

In [118]:
df_territorio_especial_pt2

,Unnamed: 0,cod_tipo_nome,valor_transacao,perc_valor_transacao,quantidade_contemplados,perc_quantidade_contemplados,qtd_tipo_documento_CNPJ,qtd_tipo_documento_CPF,valor_tipo_documento_CNPJ,valor_tipo_documento_CPF,min_valor_tipo_documento_CNPJ,min_valor_tipo_documento_CPF,mediana_valor_tipo_documento_CNPJ,mediana_valor_tipo_documento_CPF,max_valor_tipo_documento_CNPJ,max_valor_tipo_documento_CPF,media_valor_tipo_documento_CNPJ,media_valor_tipo_documento_CPF
0,0,Não especial,2653700009,0.93,160271,0.96,30918,129353,1479002422,1174697588,375,375,12941,3572,19987818,735000,61086,9395
1,1,Favela e Comunidade Urbana,138146185,0.05,4555,0.03,864,3691,76558971,61587214,431,400,36000,10000,22109765,400000,109214,16874
2,2,Setor com baixo patamar domiciliar,21852365,0.01,673,0.00,260,413,15226973,6625393,406,378,20000,5000,1031144,650000,59714,16082
3,3,Agrupamento quilombola,7369210,0.00,481,0.00,72,409,3509108,3860103,1034,500,29307,3200,329600,150000,52375,9532
4,4,Agrupamento indígena,5078944,0.00,254,0.00,22,232,1391182,3687762,4000,500,25883,5500,250000,294095,63236,16175
5,5,Quartel e base militar,480603,0.00,24,0.00,1,23,300000,180603,300000,1089,300000,3842,300000,50000,300000,7853
6,6,Não informado,18385602,0.01,534,0.00,135,399,15166170,3219433,380,500,20000,3000,2017102,330000,156353,8384
7,7,Agrovila do PA,540519,0.00,63,0.00,4,59,66000,474519,6000,500,20000,3334,20000,127223,16500,8043
8,8,Unidade prisional,86969,0.00,10,0.00,1,9,6870,80099,6870,800,6870,6000,6870,26880,6870,8900
9,9,Convento / hospital / ILPI / IACA,152685,0.00,13,0.00,3,10,84000,68685,4000,2000,20000,5705,60000,15000,28000,6869
10,10,Alojamento / acampamento,202508,0.00,8,0.00,0,8,0,202508,0,1000,0,8500,0,105000,0,25314